#!/bin/bash

function usage() {
    echo 
    echo " Modifies the data_registrar.csv file"
    echo " Usage:"
    echo "   $(basename $0) [options] <password> [Expires][expires]"
    echo    
    echo " Options:"
    echo "   -h  Display this help"
    echo "   -a  append entry, don't overwrite existing entries"
    echo "   -d  target file directory"
    echo 
    echo " Parameters:"
    echo "   Expires  Defaults to 3600"
    echo "   expires  Defaults to Expires"
    echo 
}

#
# Read command line parameters
#
while getopts had:? option
do
    case "$option" in
        a) APPEND=1;;
        d) DIR=$OPTARG;;
        h) usage; exit;;
        *) echo "Invalid option" 
           usage
           exit 1;;
    esac
done

shift $((OPTIND-1))
if [[ $# < 1 ]]; then 
    usage
    exit 1
fi


#
# Setup Values
#
PASSWORD=$1
EXPIRES_HDR=${2:-3600}
EXPIRES_FIELD=${3:-$EXPIRES_HDR}
NONCE=$(openssl passwd NONCE | tr '/' '%')

OUT_FILE=${DIR-.}/data_registrar.csv


#
# main
#
if [ -z "$APPEND" ]; then
    echo "SEQUENTIAL"    > $OUT_FILE
fi

echo -n "$PASSWORD;" >> $OUT_FILE
echo -n "$NONCE;" >> $OUT_FILE
echo -n "$EXPIRES_HDR;" >> $OUT_FILE
echo  "$EXPIRES_FIELD"   >> $OUT_FILE

echo
echo -e "\033[1mdata_registrar.csv\033[0m"
cat $OUT_FILE
echo


