#!/bin/bash

function usage() {
    echo 
    echo "Creates $DIR/data_reg.csv file for uac_register.sf"
    echo " Usage:"
    echo "   $(basename $0) <username> <password> [expires] [auth_user]"
    echo    
    echo " Options:"
    echo "   -h  Display this help"
    echo "   -d  Directory for the target file. Default: Current directory"
    echo 
    echo " Parameters:"
    echo "   expires  Defaults to 3600"
    echo "   auth_user  Defaults to <username>"
    echo 
}

#
# Read command line parameters
#
DIR="."
if [[ "$1" =~ -[^d] ]]; then
    usage
    exit 1
elif [ "$1" == "-d" ]; then
    DIR=$2
    shift 2
fi

if [ $# -lt 2 ]; then
    usage
    exit 1
fi


USERNAME=$1
PASSWORD=$2
EXPIRES=${3:-3600}
AUTH_USER=${4:-$USERNAME}



echo "SEQUENTIAL"    > $DIR/data_reg.csv
echo -n "$USERNAME;" >> $DIR/data_reg.csv
echo -n "[authentication username=$AUTH_USER password=$PASSWORD];" >> $DIR/data_reg.csv
echo  "$EXPIRES" >> $DIR/data_reg.csv

echo
echo -e "\033[1m$DIR/data_reg.csv\033[0m"
cat $DIR/data_reg.csv
echo


